//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "master_word")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub text: String,
    pub definition: String,
    pub pronunciation: Option<String>,
    pub audio_url: Option<String>,
    pub source: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_word::Entity")]
    UserWord,
}

impl Related<super::user_word::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserWord.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
